# -*- coding: utf-8 -*-
##########################################################
#Yalda Rostainajad
#a01076641 SET C
# GIST 8138 
#feb 6th 2025
#purpose: The purpose of this script is to perform a series of spatial analyses in ArcGIS, 
#including calculating slope, aspect, and land cover preferences, 
#and then combining them through a weighted sum to create a cost
# surface for modeling deer habitat suitability.
##########################################################
"""
Generated by ArcGIS ModelBuilder on : 2025-02-05 14:21:41
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(cellSize="Z:\\GIST_8106\\Mod04\\FortStJohnBC\\FTSTJON.gdb\\fstj_lc2000", extent="1310143.28159732 1254618.84768869 1326203.28159732 1267378.84768869 PROJCS[\"NAD_1983_Albers\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Albers\"],PARAMETER[\"False_Easting\",1000000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-126.0],PARAMETER[\"Standard_Parallel_1\",50.0],PARAMETER[\"Standard_Parallel_2\",58.5],PARAMETER[\"Latitude_Of_Origin\",45.0],UNIT[\"Meter\",1.0]]", snapRaster="Z:\\GIST_8106\\Mod04\\FortStJohnBC\\FTSTJON.gdb\\fstj_lc2000"):
        fstj_dem_2_ = arcpy.Raster("fstj_dem")
        fstj_dem = arcpy.Raster("fstj_dem")
        aspectpreference_txt = "Z:\\GIST_8106\\Mod04\\FortStJohnBC\\aspectpreference.txt"
        fstj_lc2000 = arcpy.Raster("fstj_lc2000")
        landcoverpreference_txt = "Z:\\GIST_8106\\Mod04\\FortStJohnBC\\landcoverpreference.txt"

        # Process: Slope (Slope) (sa)
        deep_slope = "Z:\\GIST_8106\\Mod04\\mod04_a01076641.gdb\\deep_slope"
        Slope = deep_slope
        deep_slope = arcpy.sa.Slope(fstj_dem_2_, "DEGREE", 1, "PLANAR", "METER", "GPU_THEN_CPU")
        deep_slope.save(Slope)


        # Process: Slice (Slice) (sa)
        deerpslp = "Z:\\GIST_8106\\Mod04\\mod04_a01076641.gdb\\deerpslp"
        Slice = deerpslp
        deerpslp = arcpy.sa.Slice(deep_slope, 10, "NATURAL_BREAKS", 1, None, None)
        deerpslp.save(Slice)


        # Process: Zonal Statistics as Table (Zonal Statistics as Table) (sa)
        slpzone = "Z:\\GIST_8106\\Mod04\\mod04_a01076641.gdb\\slpzone"
        Output_Join_Layer = ""
        arcpy.sa.ZonalStatisticsAsTable(deerpslp, "VALUE", deep_slope, slpzone, "DATA", "MIN_MAX_MEAN", "CURRENT_SLICE", [90], "AUTO_DETECT", "ARITHMETIC", 360, Output_Join_Layer)
        .save(Zonal_Statistics_as_Table)


        # Process: Aspect (Aspect) (sa)
        AspectDEM = "Z:\\GIST_8106\\Mod04\\mod04_a01076641.gdb\\AspectDEM"
        Aspect = AspectDEM
        AspectDEM = arcpy.sa.Aspect(fstj_dem, "PLANAR", "METER", "GEODESIC_AZIMUTHS", "GPU_THEN_CPU")
        AspectDEM.save(Aspect)


        # Process: Reclass by ASCII File (Reclass by ASCII File) (sa)
        deerasp = "Z:\\GIST_8106\\Mod04\\mod04_a01076641.gdb\\deerasp"
        Reclass_by_ASCII_File = deerasp
        deerasp = arcpy.sa.ReclassByASCIIFile(AspectDEM, aspectpreference_txt, "DATA")
        deerasp.save(Reclass_by_ASCII_File)


        # Process: Reclass by ASCII File (2) (Reclass by ASCII File) (3d)
        dland = "Z:\\GIST_8106\\Mod04\\mod04_a01076641.gdb\\dland"
        arcpy.ddd.ReclassByASCIIFile(in_raster=fstj_lc2000, in_remap_file=landcoverpreference_txt, out_raster=dland)
        dland = arcpy.Raster(dland)

        # Process: Weighted Sum (4) (Weighted Sum) (sa)
        dcost = "Z:\\GIST_8106\\Mod04\\mod04_a01076641.gdb\\dcost"
        Weighted_Sum_4_ = dcost
        dcost = arcpy.sa.WeightedSum(WSTable([[deerpslp, 'Value', 1], [deerasp, 'Value', 1], [dland, 'VALUE', 1]]))
        dcost.save(Weighted_Sum_4_)


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS[\"NAD_1983_Albers\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Albers\"],PARAMETER[\"False_Easting\",1000000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-126.0],PARAMETER[\"Standard_Parallel_1\",50.0],PARAMETER[\"Standard_Parallel_2\",58.5],PARAMETER[\"Latitude_Of_Origin\",45.0],UNIT[\"Meter\",1.0]]", scratchWorkspace="Z:\\GIST_8106\\Mod04\\mod04_a01076641.gdb", workspace="Z:\\GIST_8106\\Mod04\\mod04_a01076641.gdb"):
        Model()
